# Generated by Django 2.0.4 on 2020-06-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contact', models.BigIntegerField(max_length=200, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('symptoms', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
    ]
