# Generated by Django 2.0.4 on 2020-06-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
    ]
